using HairyPaws.Application.Adoption.Commands.ApproveAdoptionRequest;
using HairyPaws.Application.Adoption.Commands.CancelAdoptionRequest;
using HairyPaws.Application.Adoption.Commands.CompleteAdoptionRequest;
using HairyPaws.Application.Adoption.Commands.RejectAdoptionRequest;
using HairyPaws.Application.Adoption.Commands.StartAdoptionReview;
using HairyPaws.Application.Adoption.Commands.SubmitAdoptionRequest;
using HairyPaws.Application.Adoption.Queries.GetAdoptionRequestById;
using HairyPaws.Application.Adoption.Queries.GetMyAdoptionRequests;
using HairyPaws.Application.Adoption.Queries.GetPetAdoptionRequests;
using FluentValidation;
using HairyPaws.Application.Common.CQRS;
using HairyPaws.Application.Common.Interfaces;
using HairyPaws.Application.Donations.Commands.CancelDonation;
using HairyPaws.Application.Donations.Commands.ConfirmDonation;
using HairyPaws.Application.Donations.Commands.CreateDonation;
using HairyPaws.Application.Donations.Commands.UploadDonationReceipt;
using HairyPaws.Application.Donations.Queries.GetDonationById;
using HairyPaws.Application.Donations.Queries.GetMyDonations;
using HairyPaws.Application.Donations.Queries.GetOrganizationDonations;
using HairyPaws.Application.Events.Commands.CancelEvent;
using HairyPaws.Application.Events.Commands.CreateEvent;
using HairyPaws.Application.Events.Commands.PublishEvent;
using HairyPaws.Application.Events.Commands.UpdateEvent;
using HairyPaws.Application.Events.Commands.UploadEventImage;
using HairyPaws.Application.Events.Queries.GetEventById;
using HairyPaws.Application.Events.Queries.GetEvents;
using HairyPaws.Application.Events.Queries.GetMyEvents;
using HairyPaws.Application.Identity.Commands.AdminResetPassword;
using HairyPaws.Application.Identity.Commands.ChangePassword;
using HairyPaws.Application.Identity.Commands.Login;
using HairyPaws.Application.Identity.Commands.RefreshToken;
using HairyPaws.Application.Identity.Commands.Register;
using HairyPaws.Application.Identity.Queries.GetCurrentAuthUser;
using HairyPaws.Application.Notifications.Commands.MarkAllNotificationsAsRead;
using HairyPaws.Application.Notifications.Commands.MarkNotificationAsRead;
using HairyPaws.Application.Notifications.Queries.GetNotifications;
using HairyPaws.Application.Notifications.Queries.GetUnreadNotificationsCount;
using HairyPaws.Application.Notifications.Services;
using HairyPaws.Application.Organizations.Commands.CreateOrganization;
using HairyPaws.Application.Organizations.Commands.DeleteOrganizationDocument;
using HairyPaws.Application.Organizations.Commands.RejectOrganization;
using HairyPaws.Application.Organizations.Commands.UpdateOrganization;
using HairyPaws.Application.Organizations.Commands.UploadOrganizationDocument;
using HairyPaws.Application.Organizations.Commands.UploadOrganizationLogo;
using HairyPaws.Application.Organizations.Commands.VerifyOrganization;
using HairyPaws.Application.Organizations.Queries.GetMyOrganization;
using HairyPaws.Application.Organizations.Queries.GetOrganizationById;
using HairyPaws.Application.Organizations.Queries.GetPendingOrganizations;
using HairyPaws.Application.Pets.Commands.ArchivePet;
using HairyPaws.Application.Pets.Commands.CreatePet;
using HairyPaws.Application.Pets.Commands.DeletePetPhoto;
using HairyPaws.Application.Pets.Commands.PublishPet;
using HairyPaws.Application.Pets.Commands.UpdatePet;
using HairyPaws.Application.Pets.Commands.UploadPetPhoto;
using HairyPaws.Application.Pets.Queries.GetMyPets;
using HairyPaws.Application.Pets.Queries.GetPetById;
using HairyPaws.Application.Pets.Queries.GetPetsCatalog;
using HairyPaws.Application.Users.Commands.UpdateMyProfile;
using HairyPaws.Application.Users.Commands.UpdateUserStatus;
using HairyPaws.Application.Users.Commands.UpdateUserVerification;
using HairyPaws.Application.Users.Queries.GetMyProfile;
using HairyPaws.Application.Users.Queries.GetUsers;
using HairyPaws.Application.Visits.Commands.ApproveVisit;
using HairyPaws.Application.Visits.Commands.CancelVisit;
using HairyPaws.Application.Visits.Commands.CompleteVisit;
using HairyPaws.Application.Visits.Commands.CreateVisit;
using HairyPaws.Application.Visits.Commands.RejectVisit;
using HairyPaws.Application.Visits.Queries.GetVisitById;
using HairyPaws.Application.Visits.Queries.GetVisitsByAdoptionRequest;
using HairyPaws.Contracts.Adoption.Responses;
using HairyPaws.Contracts.Common.Responses;
using HairyPaws.Contracts.Donations.Responses;
using HairyPaws.Contracts.Events.Responses;
using HairyPaws.Contracts.Notifications.Responses;
using HairyPaws.Contracts.Organizations.Responses;
using HairyPaws.Contracts.Pets.Responses;
using HairyPaws.Contracts.Visits.Responses;
using Microsoft.Extensions.DependencyInjection;

namespace HairyPaws.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddValidatorsFromAssembly(typeof(DependencyInjection).Assembly);
        services.AddScoped<INotificationService, NotificationService>();

        services.AddScoped<ICommandHandler<RegisterCommand, HairyPaws.Contracts.Users.Responses.UserSummaryResponse>, RegisterCommandHandler>();
        services.AddScoped<ICommandHandler<LoginCommand, HairyPaws.Contracts.Identity.Responses.AuthResponse>, LoginCommandHandler>();
        services.AddScoped<ICommandHandler<RefreshTokenCommand, HairyPaws.Contracts.Identity.Responses.AuthResponse>, RefreshTokenCommandHandler>();
        services.AddScoped<ICommandHandler<ChangePasswordCommand>, ChangePasswordCommandHandler>();
        services.AddScoped<ICommandHandler<AdminResetPasswordCommand>, AdminResetPasswordCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateMyProfileCommand, HairyPaws.Contracts.Users.Responses.UserProfileResponse>, UpdateMyProfileCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateUserStatusCommand, HairyPaws.Contracts.Users.Responses.UserSummaryResponse>, UpdateUserStatusCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateUserVerificationCommand, HairyPaws.Contracts.Users.Responses.UserSummaryResponse>, UpdateUserVerificationCommandHandler>();
        services.AddScoped<ICommandHandler<CreateOrganizationCommand, OrganizationDetailResponse>, CreateOrganizationCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateOrganizationCommand, OrganizationDetailResponse>, UpdateOrganizationCommandHandler>();
        services.AddScoped<ICommandHandler<UploadOrganizationLogoCommand, OrganizationDetailResponse>, UploadOrganizationLogoCommandHandler>();
        services.AddScoped<ICommandHandler<UploadOrganizationDocumentCommand, OrganizationDocumentResponse>, UploadOrganizationDocumentCommandHandler>();
        services.AddScoped<ICommandHandler<DeleteOrganizationDocumentCommand>, DeleteOrganizationDocumentCommandHandler>();
        services.AddScoped<ICommandHandler<VerifyOrganizationCommand, OrganizationDetailResponse>, VerifyOrganizationCommandHandler>();
        services.AddScoped<ICommandHandler<RejectOrganizationCommand, OrganizationDetailResponse>, RejectOrganizationCommandHandler>();
        services.AddScoped<ICommandHandler<CreatePetCommand, PetDetailResponse>, CreatePetCommandHandler>();
        services.AddScoped<ICommandHandler<UpdatePetCommand, PetDetailResponse>, UpdatePetCommandHandler>();
        services.AddScoped<ICommandHandler<UploadPetPhotoCommand, PetPhotoResponse>, UploadPetPhotoCommandHandler>();
        services.AddScoped<ICommandHandler<DeletePetPhotoCommand>, DeletePetPhotoCommandHandler>();
        services.AddScoped<ICommandHandler<PublishPetCommand, PetDetailResponse>, PublishPetCommandHandler>();
        services.AddScoped<ICommandHandler<ArchivePetCommand, PetDetailResponse>, ArchivePetCommandHandler>();
        services.AddScoped<ICommandHandler<SubmitAdoptionRequestCommand, AdoptionRequestDetailResponse>, SubmitAdoptionRequestCommandHandler>();
        services.AddScoped<ICommandHandler<StartAdoptionReviewCommand, AdoptionRequestDetailResponse>, StartAdoptionReviewCommandHandler>();
        services.AddScoped<ICommandHandler<ApproveAdoptionRequestCommand, AdoptionRequestDetailResponse>, ApproveAdoptionRequestCommandHandler>();
        services.AddScoped<ICommandHandler<RejectAdoptionRequestCommand, AdoptionRequestDetailResponse>, RejectAdoptionRequestCommandHandler>();
        services.AddScoped<ICommandHandler<CancelAdoptionRequestCommand, AdoptionRequestDetailResponse>, CancelAdoptionRequestCommandHandler>();
        services.AddScoped<ICommandHandler<CompleteAdoptionRequestCommand, AdoptionRequestDetailResponse>, CompleteAdoptionRequestCommandHandler>();
        services.AddScoped<ICommandHandler<CreateVisitCommand, VisitResponse>, CreateVisitCommandHandler>();
        services.AddScoped<ICommandHandler<ApproveVisitCommand, VisitResponse>, ApproveVisitCommandHandler>();
        services.AddScoped<ICommandHandler<RejectVisitCommand, VisitResponse>, RejectVisitCommandHandler>();
        services.AddScoped<ICommandHandler<CancelVisitCommand, VisitResponse>, CancelVisitCommandHandler>();
        services.AddScoped<ICommandHandler<CompleteVisitCommand, VisitResponse>, CompleteVisitCommandHandler>();
        services.AddScoped<ICommandHandler<CreateDonationCommand, DonationResponse>, CreateDonationCommandHandler>();
        services.AddScoped<ICommandHandler<UploadDonationReceiptCommand, DonationResponse>, UploadDonationReceiptCommandHandler>();
        services.AddScoped<ICommandHandler<ConfirmDonationCommand, DonationResponse>, ConfirmDonationCommandHandler>();
        services.AddScoped<ICommandHandler<CancelDonationCommand, DonationResponse>, CancelDonationCommandHandler>();
        services.AddScoped<ICommandHandler<CreateEventCommand, EventDetailResponse>, CreateEventCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateEventCommand, EventDetailResponse>, UpdateEventCommandHandler>();
        services.AddScoped<ICommandHandler<UploadEventImageCommand, EventDetailResponse>, UploadEventImageCommandHandler>();
        services.AddScoped<ICommandHandler<PublishEventCommand, EventDetailResponse>, PublishEventCommandHandler>();
        services.AddScoped<ICommandHandler<CancelEventCommand, EventDetailResponse>, CancelEventCommandHandler>();
        services.AddScoped<ICommandHandler<MarkNotificationAsReadCommand, NotificationResponse>, MarkNotificationAsReadCommandHandler>();
        services.AddScoped<ICommandHandler<MarkAllNotificationsAsReadCommand>, MarkAllNotificationsAsReadCommandHandler>();

        services.AddScoped<IQueryHandler<GetCurrentAuthUserQuery, HairyPaws.Contracts.Users.Responses.UserSummaryResponse>, GetCurrentAuthUserQueryHandler>();
        services.AddScoped<IQueryHandler<GetMyProfileQuery, HairyPaws.Contracts.Users.Responses.UserProfileResponse>, GetMyProfileQueryHandler>();
        services.AddScoped<IQueryHandler<GetUsersQuery, HairyPaws.Contracts.Common.Responses.PagedResponse<HairyPaws.Contracts.Users.Responses.UserSummaryResponse>>, GetUsersQueryHandler>();
        services.AddScoped<IQueryHandler<GetMyOrganizationQuery, OrganizationDetailResponse>, GetMyOrganizationQueryHandler>();
        services.AddScoped<IQueryHandler<GetOrganizationByIdQuery, OrganizationDetailResponse>, GetOrganizationByIdQueryHandler>();
        services.AddScoped<IQueryHandler<GetPendingOrganizationsQuery, PagedResponse<OrganizationSummaryResponse>>, GetPendingOrganizationsQueryHandler>();
        services.AddScoped<IQueryHandler<GetPetByIdQuery, PetDetailResponse>, GetPetByIdQueryHandler>();
        services.AddScoped<IQueryHandler<GetPetsCatalogQuery, PagedResponse<PetListItemResponse>>, GetPetsCatalogQueryHandler>();
        services.AddScoped<IQueryHandler<GetMyPetsQuery, IReadOnlyCollection<PetListItemResponse>>, GetMyPetsQueryHandler>();
        services.AddScoped<IQueryHandler<GetMyAdoptionRequestsQuery, PagedResponse<AdoptionRequestListItemResponse>>, GetMyAdoptionRequestsQueryHandler>();
        services.AddScoped<IQueryHandler<GetAdoptionRequestByIdQuery, AdoptionRequestDetailResponse>, GetAdoptionRequestByIdQueryHandler>();
        services.AddScoped<IQueryHandler<GetPetAdoptionRequestsQuery, PagedResponse<AdoptionRequestListItemResponse>>, GetPetAdoptionRequestsQueryHandler>();
        services.AddScoped<IQueryHandler<GetVisitByIdQuery, VisitResponse>, GetVisitByIdQueryHandler>();
        services.AddScoped<IQueryHandler<GetVisitsByAdoptionRequestQuery, PagedResponse<VisitListItemResponse>>, GetVisitsByAdoptionRequestQueryHandler>();
        services.AddScoped<IQueryHandler<GetMyDonationsQuery, PagedResponse<DonationListItemResponse>>, GetMyDonationsQueryHandler>();
        services.AddScoped<IQueryHandler<GetDonationByIdQuery, DonationResponse>, GetDonationByIdQueryHandler>();
        services.AddScoped<IQueryHandler<GetOrganizationDonationsQuery, PagedResponse<DonationListItemResponse>>, GetOrganizationDonationsQueryHandler>();
        services.AddScoped<IQueryHandler<GetEventsQuery, PagedResponse<EventListItemResponse>>, GetEventsQueryHandler>();
        services.AddScoped<IQueryHandler<GetEventByIdQuery, EventDetailResponse>, GetEventByIdQueryHandler>();
        services.AddScoped<IQueryHandler<GetMyEventsQuery, PagedResponse<EventListItemResponse>>, GetMyEventsQueryHandler>();
        services.AddScoped<IQueryHandler<GetNotificationsQuery, PagedResponse<NotificationResponse>>, GetNotificationsQueryHandler>();
        services.AddScoped<IQueryHandler<GetUnreadNotificationsCountQuery, UnreadNotificationsCountResponse>, GetUnreadNotificationsCountQueryHandler>();

        return services;
    }
}
